<a href="https://colab.research.google.com/github/itspritish/util/blob/master/k_fold_crossval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier 

In [0]:
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [0]:
from sklearn.model_selection import train_test_split, cross_val_score


In [8]:
cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=3) 

array([0.86378738, 0.9148581 , 0.90100671])

In [11]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3 )

array([0.39368771, 0.41068447, 0.45973154])

In [10]:
cross_val_score(LinearRegression(), digits.data, digits.target, cv=3)

array([0.52105031, 0.56814242, 0.41943985])

In [23]:
for i in range(5,10):
  print('RFC:',np.average(cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=i)) ) #Best
  
  print('SVC:',np.average(cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=i)))#Worst
  
  print('LRC:',np.average(cross_val_score(LinearRegression(), digits.data, digits.target, cv=i))) #Worst-1
  print('==================================================================')
  




RFC: 0.9299780988793949
SVC: 0.44878680061604637
LRC: 0.5065567550630692
RFC: 0.9371710165847168
SVC: 0.47266565334061905
LRC: 0.5196255191361833
RFC: 0.934280665393857
SVC: 0.4411009490588834
LRC: 0.5145579799577943
RFC: 0.9426397694476627
SVC: 0.4739728537448459
LRC: 0.5303557272641248
RFC: 0.9455510422535434
SVC: 0.4825410045328792
LRC: 0.5230194589196412
